// Conditional copy generated by rules over real data (plan A4: "Toluca suma
// 4 victorias seguidas en casa"). Every sentence here is computed from the
// standings, fixtures or top lists in hand; when a rule has nothing to say it
// returns null and the sentence is simply not printed. No filler that would
// read the same on every page.

import type { Fixture, PlayerWithStats, StandingRow, StandingsGroup } from '@/lib/api-football';
import type { RouteLocale } from '@/lib/routes';
import { countWord, num } from './i18n';
import { statFor, topValue, zoneLabel, type TopKind } from './data';

const pl = (n: number, one: string, many: string) => (n === 1 ? one : many);

export function leaderSentence(
  rows: StandingRow[],
  locale: RouteLocale,
  scope: string,
  finished: boolean,
): string | null {
  const [a, b] = rows;
  if (!a || a.all.played === 0) return null;
  const gap = b ? a.points - b.points : 0;
  const played = a.all.played;
  if (locale === 'es') {
    const head = finished
      ? `${scope ? `${scope}: ` : ''}${a.team.name} terminó primero con ${a.points} puntos en ${played} partidos`
      : `${scope ? `${scope}: ` : ''}${a.team.name} lidera con ${a.points} puntos en ${played} partidos`;
    if (!b) return `${head}.`;
    if (gap === 0 && b.all.played < played) return `${head}; ${b.team.name} tiene los mismos puntos con ${played - b.all.played === 1 ? 'un partido' : `${countWord(played - b.all.played, locale)} partidos`} menos.`;
    if (gap === 0) return `${head}, empatado en puntos con ${b.team.name}; lo separa el desempate.`;
    return `${head}, ${countWord(gap, locale)} más que ${b.team.name}.`;
  }
  if (locale === 'pt') {
    const head = finished
      ? `${scope ? `${scope}: ` : ''}${a.team.name} terminou em primeiro com ${a.points} pontos em ${played} jogos`
      : `${scope ? `${scope}: ` : ''}${a.team.name} lidera com ${a.points} pontos em ${played} jogos`;
    if (!b) return `${head}.`;
    if (gap === 0 && b.all.played < played) return `${head}; ${b.team.name} tem os mesmos pontos com ${played - b.all.played === 1 ? 'um jogo' : `${countWord(played - b.all.played, locale)} jogos`} a menos.`;
    if (gap === 0) return `${head}, empatado em pontos com ${b.team.name}; o critério de desempate faz a diferença.`;
    return `${head}, ${countWord(gap, locale)} a mais que ${b.team.name}.`;
  }
  const head = finished
    ? `${scope ? `${scope}: ` : ''}${a.team.name} finished top with ${a.points} points from ${played} matches`
    : `${scope ? `${scope}: ` : ''}${a.team.name} lead with ${a.points} points from ${played} matches`;
  if (!b) return `${head}.`;
  if (gap === 0 && b.all.played < played) return `${head}; ${b.team.name} have the same points with ${played - b.all.played === 1 ? 'a game' : `${countWord(played - b.all.played, locale)} games`} in hand.`;
  if (gap === 0) return `${head}, level on points with ${b.team.name} and ahead on the tiebreaker.`;
  return `${head}, ${countWord(gap, locale)} ${pl(gap, 'point', 'points')} clear of ${b.team.name}.`;
}

/** Leaders of each group, for competitions played in groups/conferences. */
export function groupLeadersSentence(groups: { name: string; rows: StandingRow[] }[], locale: RouteLocale): string | null {
  const parts = groups
    .filter((g) => g.rows[0] && g.rows[0].all.played > 0)
    .map((g) => `${g.name}: ${g.rows[0].team.name} (${g.rows[0].points} ${locale === 'en' ? 'pts' : 'pts'})`);
  if (parts.length === 0) return null;
  const lead = locale === 'es' ? 'Líderes por grupo' : locale === 'pt' ? 'Líderes por grupo' : 'Group leaders';
  return `${lead}: ${parts.join('; ')}.`;
}

/** Longest current streaks from the provider's form string (most recent
 *  first). At most two sentences, longest first. */
export function streakSentences(rows: StandingRow[], locale: RouteLocale): string[] {
  const found: { team: string; kind: 'W' | 'L' | 'U'; n: number }[] = [];
  for (const r of rows) {
    const form = (r.form ?? '').toUpperCase();
    if (form.length < 3) continue;
    const first = form[0];
    let n = 0;
    while (n < form.length && form[n] === first) n++;
    if ((first === 'W' || first === 'L') && n >= 3) found.push({ team: r.team.name, kind: first, n });
    else if (form.length >= 5 && !form.slice(0, 5).includes('L') && first !== 'W') {
      found.push({ team: r.team.name, kind: 'U', n: 5 });
    }
  }
  found.sort((a, b) => b.n - a.n || (a.kind === 'W' ? -1 : 1));
  return found.slice(0, 2).map(({ team, kind, n }) => {
    const w = countWord(n, locale);
    if (locale === 'es') {
      if (kind === 'W') return `${team} suma ${w} victorias seguidas.`;
      if (kind === 'L') return `${team} acumula ${w} derrotas seguidas.`;
      return `${team} no pierde en sus últimos cinco partidos.`;
    }
    if (locale === 'pt') {
      if (kind === 'W') return `${team} soma ${w} vitórias seguidas.`;
      if (kind === 'L') return `${team} acumula ${w} derrotas seguidas.`;
      return `${team} não perde há cinco jogos.`;
    }
    if (kind === 'W') return `${team} have won ${w} in a row.`;
    if (kind === 'L') return `${team} have lost ${w} in a row.`;
    return `${team} are unbeaten in their last five.`;
  });
}

/** Best attack / best defence, only when one team stands alone on each. */
export function attackDefenceSentence(rows: StandingRow[], locale: RouteLocale): string | null {
  const played = rows.filter((r) => r.all.played > 0);
  if (played.length < 4) return null;
  const byFor = [...played].sort((a, b) => b.all.goals.for - a.all.goals.for);
  const byAgainst = [...played].sort((a, b) => a.all.goals.against - b.all.goals.against);
  const att = byFor[0].all.goals.for > byFor[1].all.goals.for ? byFor[0] : null;
  const def = byAgainst[0].all.goals.against < byAgainst[1].all.goals.against ? byAgainst[0] : null;
  if (!att && !def) return null;
  const both = att && def && att === def ? att : null;
  if (locale === 'es') {
    if (both) return `${both.team.name} tiene el mejor ataque (${both.all.goals.for} goles) y la defensa menos goleada (${both.all.goals.against} en contra).`;
    const a = att ? `${att.team.name} tiene el mejor ataque (${att.all.goals.for} goles)` : null;
    const d = def ? `${def.team.name} tiene la defensa menos goleada (${def.all.goals.against} en contra)` : null;
    return `${[a, d].filter(Boolean).join('; ')}.`;
  }
  if (locale === 'pt') {
    if (both) return `${both.team.name} tem o melhor ataque (${both.all.goals.for} gols) e a defesa menos vazada (${both.all.goals.against} sofridos).`;
    const a = att ? `${att.team.name} tem o melhor ataque (${att.all.goals.for} gols)` : null;
    const d = def ? `${def.team.name} tem a defesa menos vazada (${def.all.goals.against} sofridos)` : null;
    return `${[a, d].filter(Boolean).join('; ')}.`;
  }
  if (both) return `${both.team.name} have both the best attack (${both.all.goals.for} goals) and the meanest defence (${both.all.goals.against} conceded).`;
  const a = att ? `${att.team.name} have the best attack (${att.all.goals.for} goals)` : null;
  const d = def ? `${def.team.name} have the meanest defence (${def.all.goals.against} conceded)` : null;
  return `${[a, d].filter(Boolean).join('; ')}.`;
}

/** Best home side by points at home (needs the provider's home split). */
export function homeSentence(rows: StandingRow[], locale: RouteLocale): string | null {
  const withHome = rows.filter((r) => r.home && r.home.played >= 3);
  if (withHome.length < 4) return null;
  const pts = (r: StandingRow) => r.home!.win * 3 + r.home!.draw;
  const s = [...withHome].sort((a, b) => pts(b) - pts(a));
  if (pts(s[0]) === pts(s[1])) return null;
  const h = s[0].home!;
  if (locale === 'es') return `El mejor local es ${s[0].team.name}: ${h.win} ${pl(h.win, 'victoria', 'victorias')} en ${h.played} partidos en casa.`;
  if (locale === 'pt') return `O melhor mandante é ${s[0].team.name}: ${h.win} ${pl(h.win, 'vitória', 'vitórias')} em ${h.played} jogos em casa.`;
  return `${s[0].team.name} are the best home side: ${h.win} ${pl(h.win, 'win', 'wins')} from ${h.played} home games.`;
}

/** "X lidera con 7 goles" / ties "X e Y comparten…". */
export function topSentence(rows: PlayerWithStats[], kind: TopKind, locale: RouteLocale, leagueId: number): string | null {
  if (rows.length === 0) return null;
  const top = topValue(rows[0], kind, leagueId);
  if (top <= 0) return null;
  const tied = rows.filter((p) => topValue(p, kind, leagueId) === top);
  const names = tied.slice(0, 3).map((p) => {
    const t = statFor(p, leagueId)?.team.name;
    return t ? `${p.player.name} (${t})` : p.player.name;
  });
  const unit: Record<RouteLocale, Record<TopKind, [string, string]>> = {
    es: { scorers: ['gol', 'goles'], assists: ['asistencia', 'asistencias'], cards: ['amarilla', 'amarillas'] },
    pt: { scorers: ['gol', 'gols'], assists: ['assistência', 'assistências'], cards: ['cartão amarelo', 'cartões amarelos'] },
    en: { scorers: ['goal', 'goals'], assists: ['assist', 'assists'], cards: ['yellow card', 'yellow cards'] },
  };
  const [one, many] = unit[locale][kind];
  const u = pl(top, one, many);
  const and = locale === 'es' ? ' y ' : locale === 'pt' ? ' e ' : ' and ';
  const list = names.length > 1 ? `${names.slice(0, -1).join(', ')}${and}${names[names.length - 1]}` : names[0];
  const more = tied.length > 3;
  if (locale === 'es') {
    if (kind === 'cards') return tied.length > 1 ? `${list}${more ? ' y otros' : ''} son los más amonestados, con ${top} ${u}.` : `${list} es el más amonestado, con ${top} ${u}.`;
    return tied.length > 1 ? `${list}${more ? ' y otros' : ''} comparten el primer lugar con ${top} ${u}.` : `${list} manda con ${top} ${u}.`;
  }
  if (locale === 'pt') {
    if (kind === 'cards') return tied.length > 1 ? `${list}${more ? ' e outros' : ''} são os mais advertidos, com ${top} ${u}.` : `${list} é o mais advertido, com ${top} ${u}.`;
    return tied.length > 1 ? `${list}${more ? ' e outros' : ''} dividem a ponta com ${top} ${u}.` : `${list} lidera com ${top} ${u}.`;
  }
  if (kind === 'cards') return tied.length > 1 ? `${list}${more ? ' and others' : ''} have been booked the most, ${top} ${u} each.` : `${list} has been booked the most, with ${top} ${u}.`;
  return tied.length > 1 ? `${list}${more ? ' and others' : ''} share the lead with ${top} ${u}.` : `${list} leads with ${top} ${u}.`;
}

/** Round recap once every match of it is over: goals and biggest win. */
export function roundRecap(fixtures: Fixture[], locale: RouteLocale): string | null {
  const done = fixtures.filter((f) => f.goals.home != null && f.goals.away != null && ['FT', 'AET', 'PEN'].includes(f.fixture.status.short));
  if (done.length === 0 || done.length < fixtures.length) return null;
  const goals = done.reduce((s, f) => s + (f.goals.home ?? 0) + (f.goals.away ?? 0), 0);
  const big = [...done].sort(
    (a, b) => Math.abs(b.goals.home! - b.goals.away!) - Math.abs(a.goals.home! - a.goals.away!) || b.goals.home! + b.goals.away! - (a.goals.home! + a.goals.away!),
  )[0];
  const margin = Math.abs(big.goals.home! - big.goals.away!);
  const score = `${big.teams.home.name} ${big.goals.home}-${big.goals.away} ${big.teams.away.name}`;
  const avg = (goals / done.length).toFixed(1);
  if (locale === 'es') return `Se marcaron ${num(goals, locale)} goles en ${done.length} partidos (${avg} por partido).${margin >= 2 ? ` El resultado más abultado: ${score}.` : ''}`;
  if (locale === 'pt') return `Foram ${num(goals, locale)} gols em ${done.length} jogos (${avg.replace('.', ',')} por jogo).${margin >= 2 ? ` O placar mais elástico: ${score}.` : ''}`;
  return `${num(goals, locale)} goals in ${done.length} matches (${avg} per game).${margin >= 2 ? ` Biggest win: ${score}.` : ''}`;
}

export function singleTable(groups: StandingsGroup[]): StandingRow[] | null {
  return groups.length === 1 ? groups[0].rows : null;
}

/** Which places lead where, read from the provider's per-row zone text
 *  (never from a hardcoded rule): "Del 1.º al 8.º: Clasifica a la fase
 *  final (cuartos de final)." Only for a single table whose zones are
 *  contiguous rank ranges; anything irregular returns null. */
export function zonesSentence(rows: StandingRow[], locale: RouteLocale): string | null {
  const ranges = new Map<string, { min: number; max: number; n: number }>();
  for (const r of rows) {
    const d = r.description?.trim();
    if (!d) continue;
    const e = ranges.get(d);
    if (e) {
      e.min = Math.min(e.min, r.rank);
      e.max = Math.max(e.max, r.rank);
      e.n++;
    } else ranges.set(d, { min: r.rank, max: r.rank, n: 1 });
  }
  if (ranges.size === 0) return null;
  for (const e of ranges.values()) if (e.max - e.min + 1 !== e.n) return null;
  const ord = (n: number) => (locale === 'en' ? `${n}${n % 10 === 1 && n % 100 !== 11 ? 'st' : n % 10 === 2 && n % 100 !== 12 ? 'nd' : n % 10 === 3 && n % 100 !== 13 ? 'rd' : 'th'}` : `${n}.º`);
  const parts = [...ranges.entries()]
    .sort((a, b) => a[1].min - b[1].min)
    .map(([d, e]) => {
      const label = zoneLabel(d, locale);
      const span =
        e.min === e.max
          ? locale === 'es'
            ? `El ${ord(e.min)}`
            : locale === 'pt'
              ? `O ${e.min}º`
              : `${ord(e.min)} place`
          : locale === 'es'
            ? `Del ${ord(e.min)} al ${ord(e.max)}`
            : locale === 'pt'
              ? `Do ${e.min}º ao ${e.max}º`
              : `${ord(e.min)} to ${ord(e.max)}`;
      return `${span}: ${label}`;
    });
  const lead =
    locale === 'es'
      ? 'Según la tabla actual'
      : locale === 'pt'
        ? 'Pela tabela atual'
        : 'On the current table';
  return `${lead}: ${parts.join('; ')}.`;
}
