// Conditional copy for the daily boards, generated by rules over the day's
// real fixtures (plan A4: "texto condicional"; filler identical across pages
// is forbidden). Every sentence here states something the list below it
// shows: counts, competitions, first and last kickoff, what is live.

import { fixturePhase, type Fixture } from '@/lib/api-football';
import { competitionName } from '@/lib/competitions';
import type { RouteLocale } from '@/lib/routes';
import { timeIn } from '@/lib/timezones';
import type { CompetitionGroup } from './data';

export interface DayFacts {
  total: number;
  live: number;
  finished: number;
  first: Fixture | null;
  last: Fixture | null;
  /** [competition name, matches] in board order. */
  competitions: [string, number][];
}

export function dayFacts(groups: CompetitionGroup[], locale: RouteLocale): DayFacts {
  const all = groups.flatMap((g) => g.fixtures);
  const byTime = [...all].sort((a, b) => a.fixture.date.localeCompare(b.fixture.date));
  return {
    total: all.length,
    live: all.filter((f) => fixturePhase(f) === 'live').length,
    finished: all.filter((f) => fixturePhase(f) === 'finished').length,
    first: byTime[0] ?? null,
    last: byTime.length > 1 ? byTime[byTime.length - 1] : null,
    competitions: groups.map((g) => [competitionName(g.competition, locale), g.fixtures.length]),
  };
}

/** "Liga BetPlay, Champions League y Copa Libertadores". */
export function listJoin(items: string[], locale: RouteLocale): string {
  if (items.length <= 1) return items[0] ?? '';
  const and = locale === 'en' ? 'and' : locale === 'pt' ? 'e' : 'y';
  return `${items.slice(0, -1).join(', ')} ${and} ${items[items.length - 1]}`;
}

export function plural(n: number, one: string, many: string): string {
  return `${n} ${n === 1 ? one : many}`;
}

/** Kickoff in one or more zones: "19:30" or "19:30 ET (16:30 PT)". */
export function kickoffText(iso: string, zones: { zone: string; short?: string }[], locale: RouteLocale): string {
  const [main, ...rest] = zones;
  const head = `${timeIn(iso, main.zone, locale)}${main.short ? ` ${main.short}` : ''}`;
  if (rest.length === 0) return head;
  return `${head} (${rest.map((z) => `${timeIn(iso, z.zone, locale)}${z.short ? ` ${z.short}` : ''}`).join(', ')})`;
}

const VS: Record<RouteLocale, string> = { es: 'vs', pt: 'x', en: 'vs' };

export function matchName(f: Fixture, locale: RouteLocale): string {
  return `${f.teams.home.name} ${VS[locale]} ${f.teams.away.name}`;
}

/** "Liga BetPlay (4 partidos), Champions League (3) y MLS (1)". */
export function competitionsSentence(facts: DayFacts, locale: RouteLocale, max = 6): string {
  const word = { es: ['partido', 'partidos'], pt: ['jogo', 'jogos'], en: ['match', 'matches'] }[locale];
  const items = facts.competitions.slice(0, max).map(([name, n], i) =>
    i === 0 ? `${name} (${plural(n, word[0], word[1])})` : `${name} (${n})`,
  );
  const more = facts.competitions.length - max;
  if (more > 0) {
    items.push(locale === 'en' ? `${more} more` : locale === 'pt' ? `mais ${more}` : `${more} más`);
  }
  return listJoin(items, locale);
}

/** Up to three names, then "y más": "Liga BetPlay, MLS, Champions League y más". */
export function topCompetitions(names: string[], locale: RouteLocale, max = 3): string {
  if (names.length <= max) return listJoin(names, locale);
  const more = locale === 'en' ? 'more' : locale === 'pt' ? 'outras' : 'más';
  return `${names.slice(0, max).join(', ')} ${locale === 'en' ? 'and' : locale === 'pt' ? 'e' : 'y'} ${more}`;
}
