import type { RouteLocale } from '@/lib/routes';

export const STR = {
  es: {
    home: 'Inicio',
    guides: 'Guías',
    news: 'Noticias',
    authors: 'Autores',
    report: 'Informe Golify',
    updatedOn: 'Actualizada el',
    updatedOnNews: 'Actualizado el',
    publishedOn: 'Publicado el',
    by: 'Por',
    toc: 'En esta guía',
    faq: 'Preguntas frecuentes',
    sources: 'Fuentes',
    related: 'Datos relacionados',
    hubLabel: 'Tabla y calendario de',
    pool: 'Quiniela de',
    watch: 'Dónde ver',
    match: 'Ver el partido',
    team: 'Equipo',
    liveBlog: 'En vivo',
    liveBlogLead: 'Seguimiento minuto a minuto',
    ctaTitle: 'Llévalo en tu bolsillo',
    ctaBody: 'Marcadores en vivo, alertas de gol y tu quiniela con amigos en la app Golify.',
    open: 'Abrir Golify',
    ios: 'App Store',
    android: 'Google Play',
    guidesTitle: 'Guías de fútbol',
    guidesDesc: 'Guías claras sobre formatos, reglas y cómo jugar la quiniela, con fuentes y fecha de revisión.',
    guidesH1: 'Guías Golify',
    newsTitle: 'Noticias de fútbol',
    newsDesc: 'Previas, crónicas y análisis de la redacción de Golify con datos de partidos y de la comunidad.',
    newsH1: 'Noticias Golify',
    authorTitle: 'Autores',
    authorDesc: 'Quién escribe en Golify: la redacción y los autores de nuestras guías, previas y análisis.',
    authorH1: 'Quién escribe en Golify',
    authorPieces: 'Piezas de',
    noPieces: 'Todavía no hay piezas publicadas en este idioma.',
    readMore: 'Leer',
    pieces: 'piezas',
    langOnly: 'Disponible solo en este idioma.',
    reportTitle: 'Informe Golify mensual',
    reportDesc: 'Cada mes, lo que predijo la comunidad de Golify: aciertos, sorpresas y partidos más pronosticados.',
    reportH1: 'Informe Golify',
    reportIdx: 'Informes mensuales con los pronósticos de la comunidad de Golify en cada liga que cubrimos.',
    editorialPolicy: 'Política editorial',
    noReports: 'Todavía no hay informes.',
    month: 'Mes',
  },
  pt: {
    home: 'Início',
    guides: 'Guias',
    news: 'Notícias',
    authors: 'Autores',
    report: 'Relatório Golify',
    updatedOn: 'Atualizado em',
    updatedOnNews: 'Atualizado em',
    publishedOn: 'Publicado em',
    by: 'Por',
    toc: 'Neste guia',
    faq: 'Perguntas frequentes',
    sources: 'Fontes',
    related: 'Dados relacionados',
    hubLabel: 'Tabela e calendário:',
    pool: 'Bolão:',
    watch: 'Onde assistir',
    match: 'Ver a partida',
    team: 'Time',
    liveBlog: 'Ao vivo',
    liveBlogLead: 'Acompanhamento lance a lance',
    ctaTitle: 'Leve no bolso',
    ctaBody: 'Placares ao vivo, alertas de gol e o seu bolão com os amigos no app Golify.',
    open: 'Abrir Golify',
    ios: 'App Store',
    android: 'Google Play',
    guidesTitle: 'Guias de futebol',
    guidesDesc: 'Guias claros sobre formatos, regras e como jogar o bolão, com fontes e data de revisão.',
    guidesH1: 'Guias Golify',
    newsTitle: 'Notícias de futebol',
    newsDesc: 'Prévias, crônicas e análises da redação do Golify com dados de jogos e da comunidade.',
    newsH1: 'Notícias Golify',
    authorTitle: 'Autores',
    authorDesc: 'Quem escreve no Golify: a redação e os autores dos nossos guias, prévias e análises.',
    authorH1: 'Quem escreve no Golify',
    authorPieces: 'Textos de',
    noPieces: 'Ainda não há textos publicados neste idioma.',
    readMore: 'Ler',
    pieces: 'textos',
    langOnly: 'Disponível somente neste idioma.',
    reportTitle: 'Relatório Golify mensal',
    reportDesc: 'Todo mês, o que a comunidade do Golify previu: acertos, zebras e jogos mais palpitados.',
    reportH1: 'Relatório Golify',
    reportIdx: 'Relatórios mensais com os palpites da comunidade do Golify em cada liga que cobrimos.',
    editorialPolicy: 'Política editorial',
    noReports: 'Ainda não há relatórios.',
    month: 'Mês',
  },
  en: {
    home: 'Home',
    guides: 'Guides',
    news: 'News',
    authors: 'Authors',
    report: 'Golify Report',
    updatedOn: 'Updated on',
    updatedOnNews: 'Updated on',
    publishedOn: 'Published on',
    by: 'By',
    toc: 'In this guide',
    faq: 'Frequently asked questions',
    sources: 'Sources',
    related: 'Related data',
    hubLabel: 'Table and fixtures:',
    pool: 'Pool:',
    watch: 'Where to watch',
    match: 'See the match',
    team: 'Team',
    liveBlog: 'Live',
    liveBlogLead: 'Minute-by-minute coverage',
    ctaTitle: 'Take it in your pocket',
    ctaBody: 'Live scores, goal alerts and your pool with friends in the Golify app.',
    open: 'Open Golify',
    ios: 'App Store',
    android: 'Google Play',
    guidesTitle: 'Football guides',
    guidesDesc: 'Clear guides on formats, rules and how to play the pool, with sources and review date.',
    guidesH1: 'Golify guides',
    newsTitle: 'Football news',
    newsDesc: 'Previews, match reports and analysis from the Golify newsroom, backed by match and community data.',
    newsH1: 'Golify news',
    authorTitle: 'Authors',
    authorDesc: 'Who writes at Golify: the newsroom and the authors of our guides, previews and analysis.',
    authorH1: 'Who writes at Golify',
    authorPieces: 'Pieces by',
    noPieces: 'No pieces published in this language yet.',
    readMore: 'Read',
    pieces: 'pieces',
    langOnly: 'Available in this language only.',
    reportTitle: 'Golify monthly report',
    reportDesc: 'Every month, what the Golify community predicted: hits, upsets and the most predicted matches.',
    reportH1: 'Golify Report',
    reportIdx: 'Monthly reports with the Golify community predictions in every league we cover.',
    editorialPolicy: 'Editorial policy',
    noReports: 'No reports yet.',
    month: 'Month',
  },
} satisfies Record<RouteLocale, Record<string, string>>;

export function fmtDate(iso: string, locale: RouteLocale, time = false): string {
  const loc = { es: 'es-MX', pt: 'pt-BR', en: 'en-US' }[locale];
  const d = new Date(iso);
  const date = d.toLocaleDateString(loc, { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' });
  if (!time || iso.length <= 10) return date;
  return `${date}, ${d.toLocaleTimeString(loc, { hour: '2-digit', minute: '2-digit', timeZone: 'UTC' })} UTC`;
}
