// Page-local copy (chrome only — every fact comes from data). Voice: cercana,
// futbolera, precisa. No betting vocabulary anywhere.

import type { RouteLocale } from '@/lib/routes';

type Pos = 'Goalkeeper' | 'Defender' | 'Midfielder' | 'Attacker';

export const STR = {
  es: {
    home: 'Inicio',
    subtitle: 'Estadísticas, partidos, trayectoria y fichajes · {season}',
    facts: {
      club: 'Club',
      position: 'Posición',
      nationality: 'Nacionalidad',
      age: 'Edad',
      height: 'Estatura',
      weight: 'Peso',
      number: 'Dorsal',
      born: 'Nacimiento',
      fullName: 'Nombre completo',
    },
    years: '{n} años',
    positions: { Goalkeeper: 'Portero', Defender: 'Defensa', Midfielder: 'Mediocampista', Attacker: 'Delantero' } as Record<Pos, string>,
    positionsPlural: { Goalkeeper: 'Porteros', Defender: 'Defensas', Midfielder: 'Mediocampistas', Attacker: 'Delanteros' } as Record<Pos, string>,
    tabs: { summary: 'Resumen', stats: 'Estadísticas', matches: 'Partidos', career: 'Trayectoria', transfers: 'Fichajes', titles: 'Títulos', fc: 'Rating FC' },
    sections: 'Secciones',
    seasonTitle: 'Temporada {season}',
    seasonSum: 'Suma de {list}.',
    noSeason: 'Todavía no suma partidos oficiales en {season} en los torneos que cubrimos.',
    tiles: {
      apps: 'Partidos',
      minutes: '{n} minutos',
      goals: 'Goles',
      per90: "{v} por 90'",
      assists: 'Asistencias',
      shots: 'Tiros',
      onTarget: '{n} a puerta',
      passAcc: 'Pases precisos',
      cards: 'Tarjetas',
      cardsYellow: ['{n} amarilla', '{n} amarillas'],
      cardsRed: ['{n} roja', '{n} rojas'],
      conceded: 'Goles recibidos',
      saves: 'Atajadas',
    },
    byComp: 'Estadísticas por torneo',
    byCompSub: 'Temporadas {seasons}, con todos los torneos que registra el proveedor de datos.',
    th: { competition: 'Torneo', team: 'Equipo', apps: 'PJ', starts: 'Tit.', minutes: 'Min', goals: 'G', assists: 'A', rating: 'Rating', cards: 'Tarj.' },
    ratingNote: 'Rating: promedio de 1 a 10 calculado por el proveedor de datos (API-Football).',
    lastMatches: 'Últimos partidos',
    lastMatchesSub: 'Los últimos partidos de {team} y lo que aportó en cada uno.',
    thMatch: { date: 'Fecha', match: 'Partido', res: 'Res.', line: 'Aporte', rating: 'Rating' },
    result: { W: 'G', D: 'E', L: 'P' },
    resultLong: { W: 'Ganó', D: 'Empató', L: 'Perdió' },
    status: { bench: 'En la banca', out: 'No jugó', nodata: 'Sin datos del jugador' },
    goal: '{n} gol',
    goals: '{n} goles',
    assist: '{n} asist.',
    minutesShort: "{n}'",
    career: 'Trayectoria',
    careerNote: 'Armada con los traspasos que registra el proveedor de datos.',
    loan: 'préstamo',
    present: 'hoy',
    transfers: 'Fichajes',
    transferType: { Free: 'Libre', 'Free agent': 'Libre', Loan: 'Préstamo', 'Back from Loan': 'Regreso de préstamo', Transfer: 'Traspaso' } as Record<string, string>,
    titles: 'Títulos',
    titlesSub1: '1 título como campeón.',
    titlesSubN: '{n} títulos como campeón. Los 10 más recientes:',
    titlesSubAll: '{n} títulos como campeón.',
    nextMatch: 'Próximo partido',
    seeMatch: 'Ver el partido',
    fcTitle: 'Rating EA FC',
    fcLine: 'Media {r}',
    fcCard: 'Ver carta completa',
    similar: 'Jugadores similares',
    similarSub: '{position} de {team}',
    shirt: '#{n}',
    appEyebrow: 'App Golify',
    appTitle: 'Sigue cada gol de {name}',
    appBody: 'Marcador en vivo de cada partido de {team}, alerta al instante en cada gol y quinielas con tus amigos.',
    appBodyNoTeam: 'Marcadores en vivo, alerta al instante en cada gol y quinielas con tus amigos.',
    open: 'Abrir en Golify',
    ios: 'Descargar para iOS',
    android: 'Descargar para Android',
    faqTitle: 'Preguntas frecuentes',
    faqTeamQ: '¿En qué equipo juega {name}?',
    faqTeamA: '{name} juega en {team}{league}{since}{number}.',
    faqTeamLeague: ' ({league})',
    faqTeamSince: ' desde {year}',
    faqTeamNumber: ', con el dorsal {n}',
    faqGoalsQ: '¿Cuántos goles lleva {name} en {season}?',
    faqGoalsA: 'Lleva {goals} y {assists} en {apps} ({competitions}).',
    faqGoalsEvery: ' Marca uno cada {m} minutos.',
    faqAgeQ: '¿Cuántos años tiene {name}?',
    faqAgeA: 'Tiene {age} años. Nació el {date}{place}.',
    faqAgePlace: ' en {place}',
    faqHeightQ: '¿Cuánto mide {name}?',
    faqHeightA: '{name} mide {height}.',
    nGoals: ['{n} gol', '{n} goles'],
    nAssists: ['{n} asistencia', '{n} asistencias'],
    nApps: ['{n} partido', '{n} partidos'],
    insightEvery: 'Marca un gol cada {m} minutos en {season}.',
    insightInvolved: 'Participa en {n} goles (goles + asistencias) en {season}.',
    insightLast: 'Jugó {k} de los últimos {total} partidos de {team}{contrib}.',
    insightLastAll: 'Jugó los últimos {total} partidos de {team}{contrib}.',
    insightLastContrib: ', con {what}',
    insightTitles: 'Suma {n} títulos como campeón; el más reciente, {league} {season}.',
    insightTitle1: 'Fue campeón de {league} {season}.',
    metaTitle: '{name}: estadísticas, equipo y edad',
    metaDesc: '{name} ({position}, {team}): {apps}, {goals} y {assists} en {season}. Edad, estatura, trayectoria, fichajes y títulos.',
    metaDescNoSeason: '{name}{who}: edad, estatura, club, trayectoria, fichajes y títulos, con sus estadísticas por temporada.',
    noStream: 'Golify no transmite partidos.',
  },
  pt: {
    home: 'Início',
    subtitle: 'Estatísticas, jogos, carreira e transferências · {season}',
    facts: {
      club: 'Clube',
      position: 'Posição',
      nationality: 'Nacionalidade',
      age: 'Idade',
      height: 'Altura',
      weight: 'Peso',
      number: 'Camisa',
      born: 'Nascimento',
      fullName: 'Nome completo',
    },
    years: '{n} anos',
    positions: { Goalkeeper: 'Goleiro', Defender: 'Defensor', Midfielder: 'Meio-campista', Attacker: 'Atacante' } as Record<Pos, string>,
    positionsPlural: { Goalkeeper: 'Goleiros', Defender: 'Defensores', Midfielder: 'Meio-campistas', Attacker: 'Atacantes' } as Record<Pos, string>,
    tabs: { summary: 'Resumo', stats: 'Estatísticas', matches: 'Jogos', career: 'Carreira', transfers: 'Transferências', titles: 'Títulos', fc: 'Rating FC' },
    sections: 'Seções',
    seasonTitle: 'Temporada {season}',
    seasonSum: 'Soma de {list}.',
    noSeason: 'Ainda não tem jogos oficiais em {season} nos campeonatos que cobrimos.',
    tiles: {
      apps: 'Jogos',
      minutes: '{n} minutos',
      goals: 'Gols',
      per90: "{v} por 90'",
      assists: 'Assistências',
      shots: 'Finalizações',
      onTarget: '{n} no gol',
      passAcc: 'Passes certos',
      cards: 'Cartões',
      cardsYellow: ['{n} amarelo', '{n} amarelos'],
      cardsRed: ['{n} vermelho', '{n} vermelhos'],
      conceded: 'Gols sofridos',
      saves: 'Defesas',
    },
    byComp: 'Estatísticas por campeonato',
    byCompSub: 'Temporadas {seasons}, com todos os campeonatos que o provedor de dados registra.',
    th: { competition: 'Campeonato', team: 'Time', apps: 'J', starts: 'Tit.', minutes: 'Min', goals: 'G', assists: 'A', rating: 'Nota', cards: 'Cart.' },
    ratingNote: 'Nota: média de 1 a 10 calculada pelo provedor de dados (API-Football).',
    lastMatches: 'Últimos jogos',
    lastMatchesSub: 'Os últimos jogos do {team} e o que ele entregou em cada um.',
    thMatch: { date: 'Data', match: 'Jogo', res: 'Res.', line: 'Participação', rating: 'Nota' },
    result: { W: 'V', D: 'E', L: 'D' },
    resultLong: { W: 'Venceu', D: 'Empatou', L: 'Perdeu' },
    status: { bench: 'No banco', out: 'Não jogou', nodata: 'Sem dados do jogador' },
    goal: '{n} gol',
    goals: '{n} gols',
    assist: '{n} assist.',
    minutesShort: "{n}'",
    career: 'Carreira',
    careerNote: 'Montada com as transferências registradas pelo provedor de dados.',
    loan: 'empréstimo',
    present: 'hoje',
    transfers: 'Transferências',
    transferType: { Free: 'Livre', 'Free agent': 'Livre', Loan: 'Empréstimo', 'Back from Loan': 'Volta de empréstimo', Transfer: 'Transferência' } as Record<string, string>,
    titles: 'Títulos',
    titlesSub1: '1 título como campeão.',
    titlesSubN: '{n} títulos como campeão. Os 10 mais recentes:',
    titlesSubAll: '{n} títulos como campeão.',
    nextMatch: 'Próximo jogo',
    seeMatch: 'Ver o jogo',
    fcTitle: 'Rating EA FC',
    fcLine: 'Geral {r}',
    fcCard: 'Ver carta completa',
    similar: 'Jogadores parecidos',
    similarSub: '{position} do {team}',
    shirt: '#{n}',
    appEyebrow: 'App Golify',
    appTitle: 'Acompanhe cada gol de {name}',
    appBody: 'Placar ao vivo de cada jogo do {team}, alerta na hora de cada gol e bolões com seus amigos.',
    appBodyNoTeam: 'Placares ao vivo, alerta na hora de cada gol e bolões com seus amigos.',
    open: 'Abrir no Golify',
    ios: 'Baixar para iOS',
    android: 'Baixar para Android',
    faqTitle: 'Perguntas frequentes',
    faqTeamQ: 'Em que time joga {name}?',
    faqTeamA: '{name} joga no {team}{league}{since}{number}.',
    faqTeamLeague: ' ({league})',
    faqTeamSince: ' desde {year}',
    faqTeamNumber: ', com a camisa {n}',
    faqGoalsQ: 'Quantos gols {name} tem em {season}?',
    faqGoalsA: 'Tem {goals} e {assists} em {apps} ({competitions}).',
    faqGoalsEvery: ' Marca um a cada {m} minutos.',
    faqAgeQ: 'Quantos anos tem {name}?',
    faqAgeA: 'Tem {age} anos. Nasceu em {date}{place}.',
    faqAgePlace: ', em {place}',
    faqHeightQ: 'Qual a altura de {name}?',
    faqHeightA: '{name} tem {height}.',
    nGoals: ['{n} gol', '{n} gols'],
    nAssists: ['{n} assistência', '{n} assistências'],
    nApps: ['{n} jogo', '{n} jogos'],
    insightEvery: 'Marca um gol a cada {m} minutos em {season}.',
    insightInvolved: 'Participa de {n} gols (gols + assistências) em {season}.',
    insightLast: 'Jogou {k} dos últimos {total} jogos do {team}{contrib}.',
    insightLastAll: 'Jogou os últimos {total} jogos do {team}{contrib}.',
    insightLastContrib: ', com {what}',
    insightTitles: 'Soma {n} títulos como campeão; o mais recente, {league} {season}.',
    insightTitle1: 'Foi campeão de {league} {season}.',
    metaTitle: '{name}: estatísticas, time e idade',
    metaDesc: '{name} ({position}, {team}): {apps}, {goals} e {assists} em {season}. Idade, altura, carreira, transferências e títulos.',
    metaDescNoSeason: '{name}{who}: idade, altura, clube, carreira, transferências e títulos, com estatísticas por temporada.',
    noStream: 'O Golify não transmite jogos.',
  },
  en: {
    home: 'Home',
    subtitle: 'Stats, matches, career and transfers · {season}',
    facts: {
      club: 'Club',
      position: 'Position',
      nationality: 'Nationality',
      age: 'Age',
      height: 'Height',
      weight: 'Weight',
      number: 'Shirt',
      born: 'Born',
      fullName: 'Full name',
    },
    years: '{n} years',
    positions: { Goalkeeper: 'Goalkeeper', Defender: 'Defender', Midfielder: 'Midfielder', Attacker: 'Forward' } as Record<Pos, string>,
    positionsPlural: { Goalkeeper: 'Goalkeepers', Defender: 'Defenders', Midfielder: 'Midfielders', Attacker: 'Forwards' } as Record<Pos, string>,
    tabs: { summary: 'Overview', stats: 'Stats', matches: 'Matches', career: 'Career', transfers: 'Transfers', titles: 'Trophies', fc: 'FC rating' },
    sections: 'Sections',
    seasonTitle: 'Season {season}',
    seasonSum: 'Total across {list}.',
    noSeason: 'No official appearances yet in {season} in the competitions we cover.',
    tiles: {
      apps: 'Appearances',
      minutes: '{n} minutes',
      goals: 'Goals',
      per90: "{v} per 90'",
      assists: 'Assists',
      shots: 'Shots',
      onTarget: '{n} on target',
      passAcc: 'Pass accuracy',
      cards: 'Cards',
      cardsYellow: ['{n} yellow', '{n} yellow'],
      cardsRed: ['{n} red', '{n} red'],
      conceded: 'Goals conceded',
      saves: 'Saves',
    },
    byComp: 'Stats by competition',
    byCompSub: 'Seasons {seasons}, every competition our data provider records.',
    th: { competition: 'Competition', team: 'Team', apps: 'Apps', starts: 'Starts', minutes: 'Min', goals: 'G', assists: 'A', rating: 'Rating', cards: 'Cards' },
    ratingNote: 'Rating: 1–10 average computed by our data provider (API-Football).',
    lastMatches: 'Recent matches',
    lastMatchesSub: "{team}'s latest matches and what he contributed in each.",
    thMatch: { date: 'Date', match: 'Match', res: 'Res.', line: 'Contribution', rating: 'Rating' },
    result: { W: 'W', D: 'D', L: 'L' },
    resultLong: { W: 'Won', D: 'Drew', L: 'Lost' },
    status: { bench: 'On the bench', out: 'Did not play', nodata: 'No player data' },
    goal: '{n} goal',
    goals: '{n} goals',
    assist: '{n} ast.',
    minutesShort: "{n}'",
    career: 'Career',
    careerNote: 'Built from the transfers recorded by our data provider.',
    loan: 'loan',
    present: 'present',
    transfers: 'Transfers',
    transferType: { Free: 'Free', 'Free agent': 'Free agent', Loan: 'Loan', 'Back from Loan': 'Back from loan', Transfer: 'Transfer' } as Record<string, string>,
    titles: 'Trophies',
    titlesSub1: '1 title as champion.',
    titlesSubN: '{n} titles as champion. The 10 most recent:',
    titlesSubAll: '{n} titles as champion.',
    nextMatch: 'Next match',
    seeMatch: 'See the match',
    fcTitle: 'EA FC rating',
    fcLine: 'Overall {r}',
    fcCard: 'See the full card',
    similar: 'Similar players',
    similarSub: '{position} at {team}',
    shirt: '#{n}',
    appEyebrow: 'Golify app',
    appTitle: 'Follow every {name} goal',
    appBody: 'Live score for every {team} match, an instant alert on every goal and pools with your friends.',
    appBodyNoTeam: 'Live scores, an instant alert on every goal and pools with your friends.',
    open: 'Open in Golify',
    ios: 'Download for iOS',
    android: 'Download for Android',
    faqTitle: 'Frequently asked questions',
    faqTeamQ: 'What team does {name} play for?',
    faqTeamA: '{name} plays for {team}{league}{since}{number}.',
    faqTeamLeague: ' ({league})',
    faqTeamSince: ', where he has played since {year}',
    faqTeamNumber: ', wearing number {n}',
    faqGoalsQ: 'How many goals has {name} scored in {season}?',
    faqGoalsA: '{goals} and {assists} in {apps} ({competitions}).',
    faqGoalsEvery: ' That is one every {m} minutes.',
    faqAgeQ: 'How old is {name}?',
    faqAgeA: '{age} years old. Born on {date}{place}.',
    faqAgePlace: ' in {place}',
    faqHeightQ: 'How tall is {name}?',
    faqHeightA: '{name} is {height} tall.',
    nGoals: ['{n} goal', '{n} goals'],
    nAssists: ['{n} assist', '{n} assists'],
    nApps: ['{n} appearance', '{n} appearances'],
    insightEvery: 'Scores a goal every {m} minutes in {season}.',
    insightInvolved: 'Involved in {n} goals (goals + assists) in {season}.',
    insightLast: 'Played {k} of {team}’s last {total} matches{contrib}.',
    insightLastAll: 'Played each of {team}’s last {total} matches{contrib}.',
    insightLastContrib: ', with {what}',
    insightTitles: '{n} titles as champion; the most recent, {league} {season}.',
    insightTitle1: 'Won {league} {season}.',
    metaTitle: '{name}: stats, team and age',
    metaDesc: '{name} ({position}, {team}): {apps}, {goals} and {assists} in {season}. Age, height, career, transfers and trophies.',
    metaDescNoSeason: '{name}{who}: age, height, club, career, transfers and trophies, with season-by-season stats.',
    noStream: 'Golify does not stream matches.',
  },
} as const;

export type Strings = (typeof STR)[RouteLocale];

export function t(locale: RouteLocale): Strings {
  return STR[locale];
}

/** "{n} gol" / "{n} goles" */
export function plural(forms: readonly [string, string], count: number, locale: RouteLocale): string {
  return (count === 1 ? forms[0] : forms[1]).replace('{n}', count.toLocaleString(locale === 'pt' ? 'pt-BR' : locale === 'en' ? 'en-US' : 'es-MX'));
}

export function positionLabel(pos: string | null, locale: RouteLocale, pluralForm = false): string | null {
  if (!pos) return null;
  const table = pluralForm ? STR[locale].positionsPlural : STR[locale].positions;
  return (table as Record<string, string>)[pos] ?? pos;
}

/** Placeholder fill for sentence FRAGMENTS (" desde 2024"): unlike
 *  site.fill it keeps leading/trailing spaces, which the fragment needs to
 *  join the sentence it is spliced into. */
export function sub(template: string, values: Record<string, string>): string {
  return template.replace(/\{(\w+)\}/g, (_, k: string) => values[k] ?? '');
}
